[package]
name = "component_model"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true

[features]
value-imports-exports = []

[dependencies]
telomere_wasm.workspace = true
tokio.workspace = true
wat = "1.236.0"
anyhow.workspace = true
binary_reader.workspace = true
thiserror.workspace = true
