[package]
name = "telomere-component"
description = "WebAssembly Component Model decoder, IR, linker, and runtime for telomere."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true

[dependencies]
telomere.workspace = true
thiserror = "2.0.11"
tracing = { version = "0.1.41" }
num-derive = "0.4.2"
num-traits = "0.2.19"
semver = "1.0.26"
typed-arena = "2.0.2"
futures = "0.3.31"
smallvec.workspace = true

[dev-dependencies]
tracing-subscriber = { version = "0.3.19" }
wast = { version = "243.0.0", features = ["component-model"] }
wat = "1.243.0"
anyhow = { version = "1.0.98", features = ["backtrace"] }
criterion = { version = "0.6.0", features = ["async_tokio", "html_reports"] }
tokio.workspace = true

[[bench]]
name = "telomere_component_bench"
harness = false

[features]
default = []
component-gated-feature-value-imports-exports = []
component-gated-feature-nested-namespaces-and-packages = []
component-gated-feature-async = []
component-gated-feature-threading-builtins = []
component-gated-feature-fixed-length-lists = []
component-gated-feature-error-context-type = []
