[package]
name = "telomere-cli"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
anyhow = "1.0.98"
telomere.workspace = true
tokio.workspace = true

[workspace]
resolver = "2"
members = [
    "crates/telomere",
    "crates/telomere-macros",
    "crates/union-find"
]

[workspace.package]
version = "0.1.0"
rust-version = "1.86.0"
edition = "2021"
publish = false
authors = ["sizumita", "tignear"]
homepage = "https://github.com/yieldspace/telomere"
keywords = ["webassembly", "runtime"]

[workspace.dependencies]
telomere = { path = "crates/telomere" }
union-find = {path = "crates/union-find"}
telomere-macros = { path = "crates/telomere-macros" }
tokio = { version = "1.0", features = ["full"] }

regex = "1.11.1"

[profile.release]
codegen-units = 16
