(component
  (type $ty-wasi:io/error@0.2.6 (;0;)
    (instance
      (export (;0;) "error" (type (sub resource)))
    )
  )
  (import "wasi:io/error@0.2.6" (instance $wasi:io/error@0.2.6 (;0;) (type $ty-wasi:io/error@0.2.6)))
  (alias export $wasi:io/error@0.2.6 "error" (type $error (;1;)))
  (type $ty-wasi:io/streams@0.2.6 (;2;)
    (instance
      (export (;0;) "output-stream" (type (sub resource)))
      (alias outer 1 $error (type (;1;)))
      (export (;2;) "error" (type (eq 1)))
      (type (;3;) (own 2))
      (type (;4;) (variant (case "last-operation-failed" 3) (case "closed")))
      (export (;5;) "stream-error" (type (eq 4)))
      (type (;6;) (borrow 0))
      (type (;7;) (list u8))
      (type (;8;) (result (error 5)))
      (type (;9;) (func (param "self" 6) (param "contents" 7) (result 8)))
      (export (;0;) "[method]output-stream.blocking-write-and-flush" (func (type 9)))
    )
  )
  (import "wasi:io/streams@0.2.6" (instance $wasi:io/streams@0.2.6 (;1;) (type $ty-wasi:io/streams@0.2.6)))
  (alias export $wasi:io/streams@0.2.6 "output-stream" (type $output-stream (;3;)))
  (type $ty-wasi:cli/stdout@0.2.6 (;4;)
    (instance
      (alias outer 1 $output-stream (type (;0;)))
      (export (;1;) "output-stream" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "get-stdout" (func (type 3)))
    )
  )
  (import "wasi:cli/stdout@0.2.6" (instance $wasi:cli/stdout@0.2.6 (;2;) (type $ty-wasi:cli/stdout@0.2.6)))
  (core module $main (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32 i32 i32 i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;3;) (func))
    (type (;4;) (func (param i32)))
    (import "cm32p2|wasi:cli/stdout@0.2" "get-stdout" (func $get-stdout (;0;) (type 0)))
    (import "cm32p2|wasi:io/streams@0.2" "[method]output-stream.blocking-write-and-flush" (func $write-and-flush (;1;) (type 1)))
    (memory (;0;) 1)
    (export "cm32p2_memory" (memory 0))
    (export "cm32p2_realloc" (func 2))
    (export "cm32p2_initialize" (func 3))
    (export "cm32p2|wasi:cli/run@0.2|run" (func $run))
    (export "cm32p2|wasi:cli/run@0.2|run_post" (func 5))
    (func (;2;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;3;) (type 3))
    (func $run (;4;) (type 0) (result i32)
      call $get-stdout
      i32.const 0
      i32.const 41
      i32.const 1024
      call $write-and-flush
      i32.const 0
    )
    (func (;5;) (type 4) (param i32))
    (data (;0;) (i32.const 0) "hello from telomere (wasi 0.2 component)\0a")
    (@producers
      (processed-by "wit-component" "0.255.0")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32 i32 i32 i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func 0))
    (export "$imports" (table 0))
    (func (;0;) (type 0) (param i32 i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "0.255.0")
    )
  )
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32 i32 i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "0.255.0")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias export $wasi:cli/stdout@0.2.6 "get-stdout" (func $get-stdout (;0;)))
  (core func $get-stdout (;0;) (canon lower (func $get-stdout)))
  (core instance $cm32p2|wasi:cli/stdout@0.2 (;1;)
    (export "get-stdout" (func $get-stdout))
  )
  (alias core export $wit-component-shim-instance "0" (core func $"indirect-cm32p2|wasi:io/streams@0.2-[method]output-stream.blocking-write-and-flush" (;1;)))
  (core instance $cm32p2|wasi:io/streams@0.2 (;2;)
    (export "[method]output-stream.blocking-write-and-flush" (func $"indirect-cm32p2|wasi:io/streams@0.2-[method]output-stream.blocking-write-and-flush"))
  )
  (core instance $main (;3;) (instantiate $main
      (with "cm32p2|wasi:cli/stdout@0.2" (instance $cm32p2|wasi:cli/stdout@0.2))
      (with "cm32p2|wasi:io/streams@0.2" (instance $cm32p2|wasi:io/streams@0.2))
    )
  )
  (alias core export $main "cm32p2_memory" (core memory $memory (;0;)))
  (alias core export $wit-component-shim-instance "$imports" (core table $"shim table" (;0;)))
  (alias export $wasi:io/streams@0.2.6 "[method]output-stream.blocking-write-and-flush" (func $"[method]output-stream.blocking-write-and-flush" (;1;)))
  (alias core export $main "cm32p2_realloc" (core func $realloc (;2;)))
  (core func $"#core-func3 indirect-cm32p2|wasi:io/streams@0.2-[method]output-stream.blocking-write-and-flush" (@name "indirect-cm32p2|wasi:io/streams@0.2-[method]output-stream.blocking-write-and-flush") (;3;) (canon lower (func $"[method]output-stream.blocking-write-and-flush") (memory $memory)))
  (core instance $fixup-args (;4;)
    (export "$imports" (table $"shim table"))
    (export "0" (func $"#core-func3 indirect-cm32p2|wasi:io/streams@0.2-[method]output-stream.blocking-write-and-flush"))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "" (instance $fixup-args))
    )
  )
  (alias core export $main "cm32p2_initialize" (core func $start (;4;)))
  (core module $start-shim-module (;3;)
    (type (;0;) (func))
    (import "" "" (func (;0;) (type 0)))
    (start 0)
  )
  (core instance $start-shim-args (;6;)
    (export "" (func $start))
  )
  (core instance $start-shim-instance (;7;) (instantiate $start-shim-module
      (with "" (instance $start-shim-args))
    )
  )
  (type (;5;) (result))
  (type (;6;) (func (result 5)))
  (alias core export $main "cm32p2|wasi:cli/run@0.2|run" (core func $cm32p2|wasi:cli/run@0.2|run (;5;)))
  (alias core export $main "cm32p2|wasi:cli/run@0.2|run_post" (core func $cm32p2|wasi:cli/run@0.2|run_post (;6;)))
  (func $run (;2;) (type 6) (canon lift (core func $cm32p2|wasi:cli/run@0.2|run) (post-return $cm32p2|wasi:cli/run@0.2|run_post)))
  (component $wasi:cli/run@0.2.6-shim-component (;0;)
    (type (;0;) (result))
    (type (;1;) (func (result 0)))
    (import "import-func-run" (func (;0;) (type 1)))
    (type (;2;) (result))
    (type (;3;) (func (result 2)))
    (export (;1;) "run" (func 0) (func (type 3)))
  )
  (instance $wasi:cli/run@0.2.6-shim-instance (;3;) (instantiate $wasi:cli/run@0.2.6-shim-component
      (with "import-func-run" (func $run))
    )
  )
  (export $wasi:cli/run@0.2.6 (;4;) "wasi:cli/run@0.2.6" (instance $wasi:cli/run@0.2.6-shim-instance))
  (@producers
    (processed-by "wit-component" "0.255.0")
  )
)
