mod base;
mod error;
mod instruction;
mod parser;
mod type_checker;
mod types;
mod validate;
mod values;
pub use error::WasmParserError;
pub(crate) use instruction::InstructionParser;
pub use parser::WasmParser;
pub type Result<R> = std::result::Result<R, WasmParserError>;
pub use parser::WasmParserError;
pub use values::*;
