[package]
name = "telomere-component-wasi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
build = "build.rs"

[dependencies]
getrandom.workspace = true
libc.workspace = true
telomere.workspace = true
telomere-component = { workspace = true, features = ["component-gated-feature-async"] }
telomere-component-bindgen.workspace = true
tokio.workspace = true

[dev-dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
wat = "1.243.0"
