[package]
name = "telomere-component-wasi"
description = "WASI 0.2 host provider for telomere's Component Model runtime."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
getrandom.workspace = true
libc.workspace = true
telomere = { path = "../telomere", default-features = false }
telomere-component = { path = "../telomere-component", default-features = false }
telomere-component-bindgen.workspace = true

[dev-dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
tokio = { workspace = true, default-features = false, features = ["macros", "rt", "rt-multi-thread", "time", "sync"] }
wat = "1.243.0"

[features]
default = ["simd", "threads"]
simd = ["telomere/simd", "telomere-component/simd"]
threads = ["telomere/threads", "telomere-component/threads"]
