[package]
name = "telomere-jit-codegen"
description = "Executable memory and code emission helpers for the telomere baseline JIT."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
mmap-rs.workspace = true
