[package]
name = "telomere"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
keywords.workspace = true


[dependencies]
binary_reader.workspace = true
wide = { version = "0.7.32", optional = true }
thiserror = "2.0.11"
tracing = { version = "0.1.41" }
num-derive = "0.4.2"
num-traits = "0.2.19"
regex.workspace = true
once_cell = "1.21.3"
semver = "1.0.26"
union-find.workspace = true
typed-arena = "2.0.2"
telomere-macros.workspace = true
futures = { version = "0.3.31", optional = true }
tokio = { workspace = true, optional = true }
telomere_wasm = {workspace = true}
component_model.workspace = true

[dev-dependencies]
tracing-subscriber = { version = "0.3.19" }
wast = { version = "229.0.0", features = ["component-model"] }
wat = "1.228.0"
anyhow = { version = "1.0.98", features = ["backtrace"] }
criterion = { version = "0.6.0", features = ["async_tokio", "html_reports"] }
[[bench]]
name = "telomere_bench"
harness = false


[features]
default = ["interpreter", "simd", "async-runtime"]
interpreter = []
simd = ["wide"]
async-runtime = ["tokio", "futures"]
# 🪙
component-gated-feature-value-imports-exports = []
# 🪺
component-gated-feature-nested-namespaces-and-packages = []
# 🔀
component-gated-feature-async = []
# 🧵
component-gated-feature-threading-builtins = []
# 🔧
component-gated-feature-fixed-length-lists = []
# 📝
component-gated-feature-error-context-type = []
