#!/usr/bin/env python3
"""Generate and verify the bounded-recursion regression fixtures.

Run without arguments to regenerate the four recipe-backed files under
``fuzz/regressions``. Run with ``--check`` to prove that the generated bytes,
their fixed size/SHA-256 identities, and the committed files all agree.

The fifth fixture in this family, ``nested-recursion-stack-overflow.bin``, is a
preserved historical artifact rather than a recipe-backed fixture. ``--check``
still validates its fixed size and SHA-256 identity.
"""

from __future__ import annotations

import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
CORE_MODULE_HEADER = b"\0asm" + bytes((1, 0, 0, 0))
COMPONENT_HEADER = b"\0asm" + bytes((0x0D, 0, 1, 0))

TYPE_SECTION = 1
FUNCTION_SECTION = 3
CODE_SECTION = 10
COMPONENT_SECTION = 4
BLOCK = 0x02
EMPTY_BLOCK_TYPE = 0x40
END = 0x0B


@dataclass(frozen=True)
class GeneratedArtifact:
    relative_path: str
    recipe: Callable[[], bytes]
    expected_size: int
    expected_sha256: str


@dataclass(frozen=True)
class PreservedArtifact:
    relative_path: str
    expected_size: int
    expected_sha256: str


def encode_u32_leb128(value: int) -> bytes:
    if value < 0:
        raise ValueError(f"cannot encode a negative u32: {value}")

    encoded = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        encoded.append(byte | (0x80 if value else 0))
        if not value:
            return bytes(encoded)


def append_section(output: bytearray, section_id: int, payload: bytes) -> None:
    output.append(section_id)
    output.extend(encode_u32_leb128(len(payload)))
    output.extend(payload)


def nested_block_module(depth: int) -> bytes:
    """Build one core function with ``depth`` nested empty ``block`` instructions."""
    body = bytearray((0,))  # local declaration count
    for _ in range(depth):
        body.extend((BLOCK, EMPTY_BLOCK_TYPE))
    body.extend((END,) * (depth + 1))  # one end per block plus the function end

    module = bytearray(CORE_MODULE_HEADER)
    append_section(module, TYPE_SECTION, bytes((1, 0x60, 0, 0)))  # () -> ()
    append_section(module, FUNCTION_SECTION, bytes((1, 0)))  # one function of type 0

    code = bytearray(encode_u32_leb128(1))
    code.extend(encode_u32_leb128(len(body)))
    code.extend(body)
    append_section(module, CODE_SECTION, bytes(code))
    return bytes(module)


def nested_component_sections(depth: int) -> bytes:
    """Build ``depth`` nested component sections around an empty component.

    A component section payload is a complete component, so every wrapping
    layer starts with its own component header before section id 4 and the
    encoded payload length. This is the same wire shape as the boundary test.
    """
    component = COMPONENT_HEADER
    for _ in range(depth):
        outer = bytearray(COMPONENT_HEADER)
        append_section(outer, COMPONENT_SECTION, component)
        component = bytes(outer)
    return component


GENERATED_ARTIFACTS = (
    GeneratedArtifact(
        "fuzz/regressions/parse_core_module/nested-blocks-513.bin",
        lambda: nested_block_module(513),
        1_565,
        "0480aec8ed3ffba53276d4aa1b8d6b338b0eb6e7ddd7103e266ecdc89826fb8c",
    ),
    GeneratedArtifact(
        "fuzz/regressions/parse_core_module/nested-blocks-12000.bin",
        lambda: nested_block_module(12_000),
        36_028,
        "e0d9ab93d6ea6b86e519a31ebfe0166124b8f0bd191be16cb70cc0c0667d6a0e",
    ),
    GeneratedArtifact(
        "fuzz/regressions/decode_component/nested-components-101.bin",
        lambda: nested_component_sections(101),
        1_107,
        "44121964e79ac056902d8a7d618f7b49934e82b65ed2c0f36c9622bdefd86cc9",
    ),
    GeneratedArtifact(
        "fuzz/regressions/decode_component/nested-components-12800.bin",
        lambda: nested_component_sections(12_800),
        152_106,
        "4a7812749ea5f9bcc7d46b445f41251983bbfe644d30503a1cf421bc90266db8",
    ),
)

PRESERVED_ARTIFACT = PreservedArtifact(
    "fuzz/regressions/decode_component/nested-recursion-stack-overflow.bin",
    2_865,
    "8cbcfff5383d040079ab5952206276b0da250a95b536061ac19682d7e99e5f7f",
)


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def validate_identity(relative_path: str, data: bytes, expected_size: int, expected_sha256: str) -> list[str]:
    failures = []
    if len(data) != expected_size:
        failures.append(
            f"{relative_path}: expected {expected_size} bytes, got {len(data)}"
        )
    actual_sha256 = sha256_hex(data)
    if actual_sha256 != expected_sha256:
        failures.append(
            f"{relative_path}: expected SHA-256 {expected_sha256}, got {actual_sha256}"
        )
    return failures


def generate() -> int:
    for artifact in GENERATED_ARTIFACTS:
        data = artifact.recipe()
        failures = validate_identity(
            artifact.relative_path,
            data,
            artifact.expected_size,
            artifact.expected_sha256,
        )
        if failures:
            for failure in failures:
                print(f"generate_recursion_regressions: {failure}", file=sys.stderr)
            return 1

        destination = REPOSITORY_ROOT / artifact.relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        print(
            f"generated {artifact.relative_path} "
            f"bytes={len(data)} sha256={sha256_hex(data)}"
        )
    return 0


def check() -> int:
    failures = []
    for artifact in GENERATED_ARTIFACTS:
        generated = artifact.recipe()
        failures.extend(
            validate_identity(
                artifact.relative_path,
                generated,
                artifact.expected_size,
                artifact.expected_sha256,
            )
        )

        destination = REPOSITORY_ROOT / artifact.relative_path
        try:
            committed = destination.read_bytes()
        except OSError as error:
            failures.append(f"{artifact.relative_path}: failed to read committed artifact: {error}")
            continue
        failures.extend(
            validate_identity(
                artifact.relative_path,
                committed,
                artifact.expected_size,
                artifact.expected_sha256,
            )
        )
        if committed != generated:
            failures.append(
                f"{artifact.relative_path}: committed bytes differ from generator output"
            )

    preserved_path = REPOSITORY_ROOT / PRESERVED_ARTIFACT.relative_path
    try:
        preserved = preserved_path.read_bytes()
    except OSError as error:
        failures.append(
            f"{PRESERVED_ARTIFACT.relative_path}: failed to read preserved artifact: {error}"
        )
    else:
        failures.extend(
            validate_identity(
                PRESERVED_ARTIFACT.relative_path,
                preserved,
                PRESERVED_ARTIFACT.expected_size,
                PRESERVED_ARTIFACT.expected_sha256,
            )
        )

    if failures:
        for failure in failures:
            print(f"generate_recursion_regressions: {failure}", file=sys.stderr)
        return 1

    for artifact in GENERATED_ARTIFACTS:
        print(
            f"verified {artifact.relative_path} "
            f"bytes={artifact.expected_size} sha256={artifact.expected_sha256}"
        )
    print(
        f"verified {PRESERVED_ARTIFACT.relative_path} "
        f"bytes={PRESERVED_ARTIFACT.expected_size} "
        f"sha256={PRESERVED_ARTIFACT.expected_sha256}"
    )
    return 0


def main(argv: list[str]) -> int:
    if not argv:
        return generate()
    if argv == ["--check"]:
        return check()
    print("usage: tools/generate_recursion_regressions.py [--check]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
